# Generated by Django 6.1 on 2026-08-23 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_participacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participacion',
            options={'verbose_name': 'Participación', 'verbose_name_plural': 'Participaciones'},
        ),
        migrations.AddField(
            model_name='tarea',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_responsables', to='core.participacion'),
        ),
    ]
