# Generated by Django 6.1 on 2026-08-23 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_participacion_options_tarea_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_responsables', to='core.participacion'),
        ),
    ]
