# Generated by Django 6.1 on 2026-08-23 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tarea_responsable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='estados',
            new_name='estado',
        ),
    ]
