# Generated by Django 6.1 on 2026-08-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_estados_tarea_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='importancia',
            new_name='prioridad',
        ),
    ]
